services:
  django:
    build: ./django
    container_name: django
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./project:/project
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword