# Generated by Django 5.1.3 on 2024-11-20 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_players', models.IntegerField(choices=[(0, 'Play Local'), (1, 'Play with AI'), (2, '2 Players'), (3, '3 Players')], default=2)),
                ('nbPlayer', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='active', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='parties_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_party',
            },
        ),
    ]
