# Generated by Django 5.1.3 on 2024-11-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Musclor : Le Défenseur d’Eternia, un guerrier puissant qui manie l’Épée de Pouvoir et protège les secrets du Château des Ombres.'),
        ),
    ]
