# Generated by Django 5.1.3 on 2024-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Cobra : L’Aventurier de l’Espace, un aventurier rusé avec un Psychogun et un talent pour déjouer ses ennemis.'),
        ),
    ]
